name: Linux
on:
  push:
  pull_request:
jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os:
          - debian-buster
          - ubuntu-bionic
          - centos-6
          - centos-7
          - centos-8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt -V install ruby
      - name: Build deb with Docker
        if: matrix.os == 'debian-buster' || matrix.os == 'ubuntu-bionic'
        run: |
          rake apt:build APT_TARGETS=${{ matrix.os }}
      - name: Build rpm with Docker
        if: matrix.os == 'centos-6' || matrix.os == 'centos-7' || matrix.os == 'centos-8'
        run: |
          rake yum:build YUM_TARGETS=${{ matrix.os }}
      - uses: actions/upload-artifact@master
        if: matrix.os == 'debian-buster' || matrix.os == 'ubuntu-bionic'
        with:
          name: packages-${{ matrix.os }}
          path: td-agent/apt/repositories
      - uses: actions/upload-artifact@master
        if: matrix.os == 'centos-6' || matrix.os == 'centos-7' || matrix.os == 'centos-8'
        with:
          name: packages-${{ matrix.os }}
          path: td-agent/yum/repositories
