name: macOS
on:
  push:
    branches: [master]
  pull_request:
jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - name: Install cmake
        run: |
          brew install cmake
      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - name: Install gems
        run: |
          gem install bundler builder
      - name: Build
        run: |
          sudo mkdir /opt/fluent
          sudo chown $(whoami) /opt/fluent
          rm -rf fluent/staging
          rake dmg:selfbuild PATH="$HOME/.cargo/bin:$PATH"
      - name: Upload fluent-package dmg
        uses: actions/upload-artifact@master
        with:
          name: packages-macos
          path: fluent-package/dmg/*.dmg
  test:
    name: Test
    needs: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@master
        with:
          name: packages-macos
      - name: Run test
        run: fluent-package/dmg/install-test.sh *.dmg
