name: Yum based Linux (AArch64)
on:
  workflow_dispatch:
concurrency:
  group: ${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        label:
          - RockyLinux 8 aarch64
          - AlmaLinux 9 aarch64
          - Amazon Linux 2 aarch64
          # It takes too long time on GitHub Actions.
          #- Amazon Linux 2023 aarch64
        include:
          - label: RockyLinux 8 aarch64
            rake-job: rockylinux-8
            test-docker-image: rockylinux:8
          - label: AlmaLinux 9 aarch64
            rake-job: almalinux-9
            test-docker-image: almalinux:9
          - label: Amazon Linux 2 aarch64
            rake-job: amazonlinux-2
            test-docker-image: amazonlinux:2
          #- label: Amazon Linux 2023 aarch64
          #  rake-job: amazonlinux-2023
          #  test-docker-image: amazonlinux:2023
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt -V install ruby ruby-bundler ruby-serverspec
          sudo apt -V install qemu-user-static
          sudo gem install bundler:2.2.9 --no-document
          sudo gem uninstall fileutils
      - name: Build rpm with Docker
        run: |
          cp /usr/bin/qemu-aarch64-static fluent-package/yum/${{ matrix.rake-job }}/
          rake yum:build YUM_TARGETS=${{ matrix.rake-job }}-aarch64
      - name: Upload fluent-package rpm
        uses: actions/upload-artifact@master
        with:
          name: packages-${{ matrix.rake-job }}-aarch64
          path: fluent-package/yum/repositories
      - name: Check Package Size
        run: |
          fluent-package/yum/pkgsize-test.sh ${{ matrix.rake-job }} aarch64
      - name: Binstubs Test
        run: |
          mkdir -p .bundle
          docker run \
          --rm \
          --tty \
          --volume ${PWD}:/fluentd:ro \
          --env CENTOS_STREAM=false \
          arm64v8/${{ matrix.test-docker-image }} \
          /fluentd/fluent-package/yum/binstubs-test.sh
